// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('d:/Users/samru/Documents/Seek/node_modules/react');
var { Component } = React;
var ReactNative = require('d:/Users/samru/Documents/Seek/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('Seek', appParameters);
});
require('d:/Users/samru/Documents/Seek/index.js');